export const GameAbi = [
	{
		type: "constructor",
		inputs: [
			{
				name: "_channelHost",
				type: "address",
				internalType: "address",
			},
			{ name: "_treasury", type: "address", internalType: "address" },
		],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "balance",
		inputs: [
			{ name: "", type: "address", internalType: "address" },
			{ name: "", type: "string", internalType: "string" },
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "buy",
		inputs: [
			{ name: "castHash", type: "string", internalType: "string" },
			{ name: "data", type: "bytes", internalType: "bytes" },
			{ name: "signature", type: "bytes", internalType: "bytes" },
		],
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "channelHost",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "creatorFeePercent",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "endTime",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "feePercent",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "isPaused",
		inputs: [],
		outputs: [{ name: "", type: "bool", internalType: "bool" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "nonce",
		inputs: [{ name: "", type: "string", internalType: "string" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "owner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "payout",
		inputs: [
			{ name: "winners", type: "address[]", internalType: "address[]" },
			{ name: "amounts", type: "uint256[]", internalType: "uint256[]" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "protocolTreasury",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "referralFeePercent",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "renounceOwnership",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "sell",
		inputs: [
			{ name: "castHash", type: "string", internalType: "string" },
			{ name: "data", type: "bytes", internalType: "bytes" },
			{ name: "signature", type: "bytes", internalType: "bytes" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "startGame",
		inputs: [
			{
				name: "_tradingEndTime",
				type: "uint256",
				internalType: "uint256",
			},
			{ name: "_endTime", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "supply",
		inputs: [{ name: "", type: "string", internalType: "string" }],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "tradingEndTime",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "transferOwnership",
		inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "updateChannelHost",
		inputs: [
			{ name: "_channelHost", type: "address", internalType: "address" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "updateGameStatus",
		inputs: [{ name: "_isPaused", type: "bool", internalType: "bool" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "updateProtocolTreasury",
		inputs: [
			{
				name: "_protocolTreasury",
				type: "address",
				internalType: "address",
			},
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "GameStarted",
		inputs: [
			{
				name: "tradingEndTime",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "endTime",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "OwnershipTransferred",
		inputs: [
			{
				name: "previousOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "newOwner",
				type: "address",
				indexed: true,
				internalType: "address",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Purchased",
		inputs: [
			{
				name: "buyer",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "castCreator",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "senderFid",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "castHash",
				type: "string",
				indexed: false,
				internalType: "string",
			},
			{
				name: "referrer",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "price",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "Sold",
		inputs: [
			{
				name: "seller",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "castCreator",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "senderFid",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "castHash",
				type: "string",
				indexed: false,
				internalType: "string",
			},
			{
				name: "referrer",
				type: "address",
				indexed: false,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
			{
				name: "price",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{ type: "error", name: "ECDSAInvalidSignature", inputs: [] },
	{
		type: "error",
		name: "ECDSAInvalidSignatureLength",
		inputs: [{ name: "length", type: "uint256", internalType: "uint256" }],
	},
	{
		type: "error",
		name: "ECDSAInvalidSignatureS",
		inputs: [{ name: "s", type: "bytes32", internalType: "bytes32" }],
	},
	{ type: "error", name: "GameNotActive", inputs: [] },
	{ type: "error", name: "GameNotOver", inputs: [] },
	{ type: "error", name: "InsufficientBalance", inputs: [] },
	{ type: "error", name: "InsufficientPayment", inputs: [] },
	{ type: "error", name: "InvalidParams", inputs: [] },
	{ type: "error", name: "InvalidSignature", inputs: [] },
	{ type: "error", name: "MaxSupply", inputs: [] },
	{
		type: "error",
		name: "OwnableInvalidOwner",
		inputs: [{ name: "owner", type: "address", internalType: "address" }],
	},
	{
		type: "error",
		name: "OwnableUnauthorizedAccount",
		inputs: [{ name: "account", type: "address", internalType: "address" }],
	},
	{ type: "error", name: "TransferFailed", inputs: [] },
] as const;
